jdoodle:
  enabled: true
  url: https://api.jdoodle.com/v1/execute
  client-id: 406741b41d51b95c1e07ce0e4f83f2b7
  client-secret: af0e851aee1b5231135f2915691676a4df71ca3439aedcbfcd68c208990e4e49
  language-versions:
    java:
      name: java
      version: 5
    c:
      name: c
      version: 6
    c-sharp:
      name: csharp
      version: 5
    c-plus:
      name: cpp
      version: 2
    pascal:
      name: pascal
      version: 3
    python:
      name: python3
      version: 5

task:
  task-list:
    first_level: 1
    second_level: 1
    third_level: 1
spring:
  application:
    name: diplom
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/diplom
    username: postgres
    password: root

  jpa.properties.hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true

settings:
  url: http://ege777.site # localhost