task:
  task-list:
    first_level: 1
    second_level: 1
    third_level: 1
spring:
  application:
    name: diplom
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/diplom
    username: postgres
    password: root

  jpa.properties.hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true